server:
  port: 8081

spring:
  application:
    name: client_two
  profiles:
    active: git
  cloud:
    config:
      uri: http://localhost:8888
      enabled: true
      discovery:
        enabled: true
        service-id: config-server
      retry:
        max-attempts: 3
        max-interval: 3000
        initial-interval: 3000
    bus:
      refresh:
        enabled: true
      env:
        enabled: true
      enabled: true
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-add-partitions: true
  config:
    import: "optional:configserver:"
  kafka:
    bootstrap-servers: localhost:9092

